version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
    - echo Installing dependencies...
      - pip install -r requirements.txt -t lib # Install dependencies to 'lib' directory
  build:
    commands:
    - echo Building the deployment package...
    - cd lib
    - zip -g -r9 ../deployment-package.zip .
    - cd ..
    - zip -g -r9 deployment-package.zip read_s3_file.py
  post_build:
    commands:
    - echo Build completed on `date`
    - aws s3 cp deployment-package.zip s3://lambda-function-code-bucket-009
    - echo Now updatigng the lambda function code...
    - aws lambda update-function-code --function-name first-cicd-aws-function --s3 bucket lambda-function-code-bucket-009 --s3-key deployment-package.zip
  